# Description: NConvert source layer Makefile
build-NconvertLayer:
	# Download and extract PowerShell binaries. Remove downloaded file
	curl -L -o $(ARTIFACTS_DIR)/NConvert-linux64.tgz https://download.xnview.com/NConvert-linux64.tgz
	tar zxf $(ARTIFACTS_DIR)/NConvert-linux64.tgz -C $(ARTIFACTS_DIR)
	rm $(ARTIFACTS_DIR)/NConvert-linux64.tgz
	ls -lart $(ARTIFACTS_DIR)
	ls -lart $(ARTIFACTS_DIR)/NConvert

