build-AdobePythonLayer:
# Download and extract PowerShell binaries. Remove downloaded file
	mkdir -p "$(ARTIFACTS_DIR)/python"
	# cp *.py "$(ARTIFACTS_DIR)/python"
	pip install -r requirements.txt -t "$(ARTIFACTS_DIR)/python"
